export const countries = {
  af: 'Afghanistan',
  ax: 'Åland',
  'us-ak': 'Alaska',
  'us-al': 'Alabama',
  al: 'Albania',
  as: 'American Samoa',
  ad: 'Andorra',
  ao: 'Angola',
  ai: 'Anguilla',
  aq: 'Antarctica',
  ag: 'Antigua and Barbuda',
  ar: 'Argentina',
  'us-az': 'Arizona',
  'us-ar': 'Arkansas',
  am: 'Armenia',
  aw: 'Aruba',
  at: 'Austria',
  au: 'Australia',
  az: 'Azerbaijan',
  bb: 'Barbados',
  bs: 'Bahamas',
  bh: 'Bahrain',
  bd: 'Bangladesh',
  be: 'Belgium',
  by: 'Belarus',
  bz: 'Belize',
  bj: 'Benin',
  bm: 'Bermuda',
  bt: 'Bhutan',
  bo: 'Bolivia',
  ba: 'Bosnia and Herzegovina',
  bw: 'Botswana',
  bv: 'Bouvet Island',
  br: 'Brazil',
  io: 'British Indian Ocean Territory',
  vg: 'British Virgin Islands',
  bn: 'Brunei',
  bf: 'Burkina Faso',
  bg: 'Bulgaria',
  bi: 'Burundi',
  bq: 'Caribbean Netherlands',
  ca: 'Canada',
  cm: 'Cameroon',
  cv: 'Cape Verde',
  ky: 'Cayman Islands',
  kh: 'Cambodia',
  'us-ca': 'California',
  cf: 'Central African Republic',
  td: 'Chad',
  cx: 'Christmas Island',
  cl: 'Chile',
  cn: 'China',
  cy: 'Chipre',
  cc: 'Cocos Islands',
  co: 'Colombia',
  'us-co': 'Colorado',
  km: 'Comoros',
  cd: 'Congo (Dem. Rep.)',
  cg: 'Congo',
  'us-ct': 'Connecticut',
  ck: 'Cook Islands',
  cr: 'Costa Rica',
  hr: 'Croatia',
  cw: 'Curaçao',
  cu: 'Cuba',
  'us-de': 'Delaware',
  dk: 'Denmark',
  dj: 'Djibouti',
  dm: 'Dominica',
  do: 'Dominican Republic',
  tl: 'East Timor',
  ec: 'Ecuador',
  eg: 'Egypt',
  sv: 'El Salvador',
  'gb-eng': 'England',
  er: 'Eritrea',
  ee: 'Estonia',
  eu: 'European Union',
  gq: 'Equatorial Guinea',
  et: 'Ethiopia',
  fk: 'Falkland Islands',
  fo: 'Faroe Islands',
  fj: 'Fiji',
  fi: 'Finland',
  'us-fl': 'Florida',
  fr: 'France',
  tf: 'French Southern and Antarctic Lands',
  pf: 'French Polynesia',
  gf: 'French Guiana',
  ga: 'Gabon',
  gm: 'Gambia',
  ge: 'Georgia',
  'us-ga': 'Georgia',
  dz: 'Germany',
  gh: 'Ghana',
  gi: 'Gibraltar',
  gd: 'Granada',
  gr: 'Greece',
  gl: 'Greenland',
  gp: 'Guadalupe',
  gu: 'Guam',
  gt: 'Guatemala',
  gg: 'Guernsey',
  gn: 'Guinea',
  gw: 'Guinea-Bissau',
  gy: 'Guyana',
  ht: 'Haiti',
  'us-hi': 'Hawaii',
  hm: 'Heard and McDonald Islands',
  hn: 'Honduras',
  hk: 'Hong Kong',
  hu: 'Hungary',
  is: 'Iceland',
  'us-id': 'Idaho',
  'us-il': 'Illinois',
  'us-in': 'Indiana',
  in: 'India',
  id: 'Indonesia',
  ir: 'Iran',
  iq: 'Iraq',
  ie: 'Ireland',
  im: 'Isle of Man',
  il: 'Israel',
  'us-ia': 'Iowa',
  it: 'Italy',
  ci: 'Ivory Coast',
  jm: 'Jamaica',
  jp: 'Japan',
  je: 'Jersey',
  jo: 'Jordania',
  'us-ks': 'Kansas',
  kz: 'Kazakhstan',
  ki: 'Kiribati',
  'us-ky': 'Kentucky',
  ke: 'Kenya',
  xk: 'Kosovo',
  kw: 'Kuwait',
  kg: 'Kyrgyzstan',
  la: 'Laos',
  lv: 'Latvia',
  lb: 'Lebanon',
  ls: 'Lesotho',
  li: 'Liechtenstein',
  lr: 'Liberia',
  ly: 'Libya',
  lt: 'Lithuania',
  'us-la': 'Louisiana',
  lu: 'Luxembourg',
  mo: 'Macao',
  mg: 'Madagascar',
  'us-me': 'Maine',
  mw: 'Malawi',
  my: 'Malaysia',
  mv: 'Maldives',
  ml: 'Mali',
  mt: 'Malta',
  mh: 'Marshall Islands',
  mq: 'Martinique',
  'us-md': 'Maryland',
  'us-ma': 'Massachusetts',
  mu: 'Mauricio',
  mr: 'Mauritania',
  yt: 'Mayotte',
  re: 'Meeting',
  mx: 'Mexico',
  'us-mi': 'Michigan',
  fm: 'Micronesia',
  'us-mn': 'Minnesota',
  'us-mo': 'Missouri',
  'us-ms': 'Mississippi',
  md: 'Moldova',
  'us-mt': 'Montana',
  mc: 'Monaco',
  mn: 'Mongolia',
  me: 'Montenegro',
  ms: 'Montserrat',
  ma: 'Morocco',
  mz: 'Mozambique',
  mm: 'Myanmar',
  na: 'Namibia',
  nr: 'Nauru',
  np: 'Nepal',
  'us-ne': 'Nebraska',
  nl: 'Netherlands',
  'us-nv': 'Nevada',
  nc: 'New Caledonia',
  'us-nh': 'New Hampshire',
  'us-nj': 'New Jersey',
  'us-nm': 'New Mexico',
  'us-ny': 'New York',
  nz: 'New Zealand',
  ni: 'Nicaragua',
  ne: 'Niger',
  ng: 'Nigeria',
  nu: 'Niue',
  nf: 'Norfolk Island',
  mk: 'North Macedonia',
  'us-nc': 'North Carolina',
  'us-nd': 'North Dakota',
  kp: 'North Korea',
  mp: 'Northern Mariana Islands',
  no: 'Norway',
  'us-oh': 'Ohio',
  'us-ok': 'Oklahoma',
  om: 'Oman',
  'us-or': 'Oregon',
  qa: 'Qatar',
  pk: 'Pakistan',
  pw: 'Palau',
  ps: 'Palestine',
  pa: 'Panama',
  pg: 'Papua New Guinea',
  py: 'Paraguay',
  'us-pa': 'Pennsylvania',
  pe: 'Peru',
  ph: 'Philippines',
  pn: 'Pitcairn Islands',
  pl: 'Poland',
  pt: 'Portugal',
  pr: 'Puerto Rico',
  cz: 'República Checa',
  'us-ri': 'Rhode Island',
  ro: 'Romania',
  ru: 'Russia',
  rw: 'Rwanda',
  ws: 'Samoa',
  st: 'Sao Tome and Principe',
  bl: 'Saint Bartholomew',
  sh: 'Saint Elena, Ascensión and Tristán de Acuña',
  kn: 'Saint Kitts and Nevis',
  lc: 'Saint Lucia',
  mf: 'Saint Martin (France)',
  sx: 'Saint Martin (Netherlands)',
  pm: 'Saint Peter and Miquelon',
  vc: 'Saint Vincent and the Grenadines',
  sm: 'San Marino',
  sa: 'Saudi Arabia',
  'gb-sct': 'Scotland',
  sn: 'Senegal',
  rs: 'Serbia',
  sc: 'Seychelles',
  sl: 'Sierra Leone',
  sg: 'Singapore',
  sk: 'Slovakia',
  si: 'Slovenia',
  sb: 'Solomon Islands',
  so: 'Somalia',
  za: 'South Africa',
  'us-sc': 'South Carolina',
  'us-sd': 'South Dakota',
  gs: 'South Georgia and South Sandwich Islands',
  kr: 'South Korea',
  ss: 'South Sudan',
  es: 'Spain',
  lk: 'Sri Lanka',
  sd: 'Sudan',
  sr: 'Suriname',
  sj: 'Svalbard and Jan Mayen',
  se: 'Sweden',
  ch: 'Switzerland',
  sz: 'Swaziland',
  sy: 'Syria',
  tw: 'Taiwan',
  tj: 'Tajikistan',
  tz: 'Tanzania',
  'us-tn': 'Tennessee',
  'us-tx': 'Texas',
  th: 'Thailand',
  tg: 'Togo',
  tk: 'Tokelau',
  to: 'Tonga',
  tt: 'Trinidad and Tobago',
  tn: 'Tunisia',
  tr: 'Turkey',
  tc: 'Turks and Caicos Islands',
  tm: 'Turkmenistan',
  tv: 'Tuvalu',
  ug: 'Uganda',
  ua: 'Ukraine',
  ae: 'United Arab Emirates',
  gb: 'United Kingdom',
  un: 'United Nations Organization',
  um: 'United States Minor Outlying Islands',
  us: 'United States',
  vi: 'United States Virgin Islands',
  uy: 'Uruguay',
  'us-ut': 'Utah',
  uz: 'Uzbekistan',
  va: 'Vatican City',
  vu: 'Vanuatu',
  ve: 'Venezuela',
  'us-vt': 'Vermont',
  vn: 'Vietnam',
  'us-va': 'Virginia',
  'gb-wls': 'Wales',
  wf: 'Wallis and Futuna',
  'us-wa': 'Washington',
  'us-wv': 'West Virginia',
  eh: 'Western Sahara',
  'us-wi': 'Wisconsin',
  'us-wy': 'Wyoming',
  ye: 'Yemen',
  zm: 'Zambia',
  zw: 'Zimbabwe',
};
